version: '3.8'

services:
  pet-manager-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pet-manager-frontend
    ports:
      - "4200:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/nginx-health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - pet-manager-network
    labels:
      - "app.name=pet-manager-frontend"
      - "app.description=Frontend Angular para gerenciamento de pets"

networks:
  pet-manager-network:
    driver: bridge
